### ISSUE TITLE
API hangs when contacting Character.AI

### ISSUE THREAD

**Issue by cyborgcatgirl** [AlizerUncaged/desktop-waifu#138]
Everything seems to load fine, it gets so far as to connect to Vtube studio, and I can send a single message with my mic, which it correctly interprets. However, it fails to ever get a response from character.AI. I've tried with and without my login key, and tried with several different characters. When it gets to this point, the CMD window title changes to "Select npt install D:\waifu\character_AI" and nothing actually appears in the prompt after my interpreted message.
![Screenshot 2023-07-12 162831](https://github.com/AlizerUncaged/desktop-waifu/assets/119764696/12458171-567f-4eef-b21e-2adda3237051)

**Comment by cyborgcatgirl** [comment]
I resolved this on my own.

**Comment by cyborgcatgirl** [comment]
I resolved this on my own

**Comment by Aadit420** [comment]
how?

**Comment by Richardo99110** [comment]
May I know how you fixed it?
