### ISSUE TITLE
Error: 'dict' object has no attribute 'text'

### ISSUE THREAD

**Issue by Aadit420** [AlizerUncaged/desktop-waifu#146]
I've tried to run whisper AI locally to prevent paying for anything and everything went well until this. I did adjust my mic settings and played the recording file. Please tell me, how do I correct this? I'd like t see this work ASAP

`Welcome back, to speak press RIGHT_CTRL.
Connecting to VTube Studio!`

`You (mic) >Authentication request sent to VTube Studio, please click allow.`

`VTube Studio connected! at port 8001`

`You (mic [Transcribing (86.1 kB)]) > C:\Users\USER\Downloads\desktop-waifu-master\waifu\lib\site-packages\whisper\transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")`

`Error: 'dict' object has no attribute 'text'`

`You (mic) >node js: C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:61
node js:         _Callback_error.set(this, new Errors_js_1.ProtocolError());
node js:                                   ^
node js:
node js: ProtocolError: Page.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
node js:     at new Callback (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:61:35)
node js:     at CallbackRegistry.create (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:106:26)
node js:     at Connection._rawSend (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:216:26)
node js:     at CDPSessionImpl.send (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:425:78)
node js:     at FrameManager.initialize (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\FrameManager.js:136:24)
node js:     at CDPPage._CDPPage_initialize (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:838:70)
node js:     at CDPPage._create (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:60:90)
node js:     at C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Target.js:128:42
node js:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node js:     at async Target.page (C:\Users\USER\Downloads\desktop-waifu-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Target.js:131:23)
node js:
node js: Node.js v19.3.0`

`You (mic [Transcribing (16.4 kB)]) > Error: 'dict' object has no attribute 'text'`
`You (mic [Recording]) >`

**Comment by Aadit420** [comment]
nvm, solved

**Comment by red085** [comment]
> nvm, solved

how?
