### ISSUE TITLE
Can't use CharacterAI_KEY correctly, start.bat logged me as guest but in the .env I put the access_token

### ISSUE THREAD

**Issue by misaki1301** [AlizerUncaged/desktop-waifu#172]
I having issues related to the script start.bat with character.ai. It doesn't recognize the token of  access_token
![image](https://github.com/AlizerUncaged/desktop-waifu/assets/22973312/102ff733-4127-483d-b18c-00475ef9c554)
maybe the API changed again?

**Comment by saipheblue** [comment]
I solved this by character_ai folder and file runner.js in vscode and changed 

await characterAI.authenticateAsGuest();

to

await client.authenticateWithToken("YOUR TOKEN")

And its working again for me, hope it helps

**Comment by misaki1301** [comment]
thanks, kinda fixed with the node wrapper of character.ai and can confirm that your solution works, hope we can make some PR to update the base code of this project
