### ISSUE TITLE
After watching the Whisper video and following the steps

### ISSUE THREAD

**Issue by DECEASEDHD** [AlizerUncaged/desktop-waifu#209]
Hello,
I've watched the video showing how to code in whisper instead of OpenAi.
But I still got this error
![image](https://github.com/AlizerUncaged/desktop-waifu/assets/149125949/f0209b8d-6958-473a-bc5e-d6604b33675b)
![image](https://github.com/AlizerUncaged/desktop-waifu/assets/149125949/1506cdf0-1926-4745-8512-b9b8bff99eff)

**Comment by carlangassnake** [comment]
So what did you do? Howd you fix that

**Comment by DECEASEDHD** [comment]
The problem was that I had other pythons and using start.bat would automatically run the most recent python, the problem was that even if I ran ''pip install [needed modules ''openai'', ''whisper ect.'' it would install it on my recent python (btw sorry for my explanation I was like 1 day new to python back then but I got it to work after 2 days) so after downloading everything I needed on the recent python I located the python location in %appdata% and copied the files from the script INTO the scripts folder of scripts (python 3.8) and imported them (so basically thought outside the box) and I also have to run, I also have to use py -3.8 to work in that folder so yeah, After that I did get more errors but fixed them

**Comment by carlangassnake** [comment]
Did it use the most recent python despite the desired version was installed where it looks for it? (C/Python310)

**Comment by DECEASEDHD** [comment]
Yes

**Comment by DECEASEDHD** [comment]
If its saying that it can't find python just copy 3.8 to the path its trying to find and rename that
