### ISSUE TITLE
no python but i did download python in a file called Python310

### ISSUE THREAD

**Issue by Lacking-some-wut-of-worth** [AlizerUncaged/desktop-waifu#217]
it keeps telling me that "No Python at 'C:\Python310\python.exe'" but did create a file in c called Python310 and i placed my python 3.12 in it . i tried getting python 3.10 but i couldnt .. i tried putting python in anther file called python.exe but it just gave me anther error. and btw the running file is called "run" not "run.bat" just wanted to make sure that that had nothing to do with it. btw i tried copping the python.exe that already existed in the downloaded files and placing it in python310 but that just gave anther error as well. currently i have deleted old files and started a new one and followed each step from the video so now im stuck again at "No Python at 'C:\Python310\python.exe" please help i have been trying for days now

**Comment by Lacking-some-wut-of-worth** [comment]
ok so i think i fixed that so um,..... now im facing this "Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\craft\Desktop\waifu\desktop-waifu-master\waifu\Src\runner.py", line 1, in <module>
    from colorama import *
ModuleNotFoundError: No module named 'colorama'
Press any key to continue . . ."

**Comment by zimavi** [comment]
run following commad: `pip install colorama` or `python.exe -m pip install colorama`

**Comment by kiraaau** [comment]
> ok so i think i fixed that so um,..... now im facing this "Could not find platform independent libraries Traceback (most recent call last): File "C:\Users\craft\Desktop\waifu\desktop-waifu-master\waifu\Src\runner.py", line 1, in from colorama import * ModuleNotFoundError: No module named 'colorama' Press any key to continue . . ."

Can you tell me how to fix  "No Python at 'C:\Python310\python.exe'"

**Comment by anjaneya49** [comment]
bro can you tell me how you fixed colorama ereor i cant fix it
