### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by Lacking-some-wut-of-worth** [AlizerUncaged/desktop-waifu#218]
Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\craft\Desktop\waifu\desktop-waifu-master\waifu\Src\runner.py", line 1, in <module>
    from colorama import *
ModuleNotFoundError: No module named 'colorama'
Press any key to continue . . .

**Comment by zimavi** [comment]
run following commad: `pip install colorama` or `python.exe -m pip install colorama`

**Comment by Lacking-some-wut-of-worth** [comment]
it just gave me error "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings" ...bro i ran the command from python. btw i did copy the orignal python file and moved it to a file called Python310, i also copied a uh something called python.dill into system23 files  bc it did not work without it.

**Comment by zimavi** [comment]
Try [this](https://stackoverflow.com/questions/65348890/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store)

**Comment by Lacking-some-wut-of-worth** [comment]
btq good new i was able to tweak some stuff and fixed that error. for some reason the files arent where the code wants them to be i was ale to find colorama and moved to where the error message said it couldnt find it. AND IT WORKED but now i got this "Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\craft\Desktop\waifu\desktop-waifu-master\waifu\Src\runner.py", line 2, in <module>
    import openai, humanize, os, sys, time, threading, asyncio, signal, json
ModuleNotFoundError: No module named 'openai'
Press any key to continue . . ." and isnt openai the place i got the key from and not a file saved on pc where i can just find it

**Comment by Lacking-some-wut-of-worth** [comment]
and i did download python from Microsoft too which fixed python not found issue (btw, sory for all this stuff i rly have no idea how python works or any of this im trying my best)

**Comment by zimavi** [comment]
Just run `pip install openai` in your cmd

**Comment by Lacking-some-wut-of-worth** [comment]
it download but i think its in wrong location " WARNING: The script openai.exe is installed in 'C:\Users\craft\AppData\Local\Package-too long  so i will try and follow error location and copy past it where it should be like i did with the ones before. btw i did retry the start thing it it gave the same openai file not found, so fixing this then i will update on the situation

**Comment by Lacking-some-wut-of-worth** [comment]
wow it worked but once again duck me (" File "C:\Users\craft\Desktop\waifu\desktop-waifu-master\waifu\Src\openai\__init__.py", line 6, in <module>
    from typing_extensions import override
ModuleNotFoundError: No module named 'typing_extensions'")

 i will have to run pip install typing_extensions and then go throu all of this again wont i 
tell me if i should or not i dont want to run something that will break my 7 yearold laptop

**Comment by Lacking-some-wut-of-worth** [comment]
SO TO SAVE THE EFFORT I COPIED EVERYTHING THAT HAAS TO DO WITH PYTHON 3.10 AND PLACED IT WHERE IT SHOULD be . now i will run start and see what happens

**Comment by Lacking-some-wut-of-worth** [comment]
ok i tried wtf do i do for this (ModuleNotFoundError: No module named 'pydantic_core._pydantic_core')

**Comment by Lacking-some-wut-of-worth** [comment]
any help?

**Comment by Azuko0** [comment]
yeah i got the same issue :)

**Comment by Lacking-some-wut-of-worth** [comment]
i fiex it but cant remmber how so i cant help oh and btw dont feel sad i got a new issue and gave up
