### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

### ISSUE THREAD

**Issue by Lacking-some-wut-of-worth** [AlizerUncaged/desktop-waifu#219]
it says "ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'" but i have the file already , maybe the file is wrong location but i dont know where to put this file

**Comment by Lacking-some-wut-of-worth** [comment]
all i want to know is where to put the pydantic_core file

**Comment by Lacking-some-wut-of-worth** [comment]
![Screenshot (6)](https://github.com/AlizerUncaged/desktop-waifu/assets/150485434/029580a7-1eb6-4f09-b269-a233f4575e9e)

**Comment by DreikalCC** [comment]
did you manage to solve this? I am stuck on this too

**Comment by DreikalCC** [comment]
ok after about an hour I have found the solution, I needed to downgrade the library with the following command:

pip install pydantic==1.*
