### ISSUE TITLE
No voice from voicevox

### ISSUE THREAD

**Issue by JackRobert94464** [AlizerUncaged/desktop-waifu#23]
ok I think I got everything running, the character replied, but I can't hear any voice from voicevox. Any idea what happened?
![image](https://github.com/AlizerUncaged/desktop-waifu/assets/100371269/f9d3ec5b-be08-4537-8035-028859a46cbc)

**Comment by JackRobert94464** [comment]
ok so apparently the problem lie here. Just posting my own fix so others with the same problem can follow. Change this to play_wav instead of play. If you code for a while, you will realise python suggest play_wav but not play, meaning there is no function named play and thus the code can't run properly.

![image](https://github.com/AlizerUncaged/desktop-waifu/assets/100371269/26351267-611b-461b-a79a-8a48b5c8b9e1)

**Comment by jamessjunk** [comment]
Can you make a video tutorial?

**Comment by LukasHSM** [comment]
Thanks a lot!! It was really enlightening. I'm gonna make sure to tell other people. My program is playing the audio perfectly now, no issues, though it's all in Japanese, I wonder how to make her speak english. Anyways, it was really helpful!
