### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by Kakonoomoide** [AlizerUncaged/desktop-waifu#236]
after I run start.bat and previously entered the required API key and when I want to record a voice or start speaking I get an error message like this

![image](https://github.com/AlizerUncaged/desktop-waifu/assets/110559394/3350588b-c40b-419d-ad35-f771c95a8b56)

is there anyone who can help

**Comment by MepleYui** [comment]
You could try using whisper locally
i did made a proper tutorial [video](https://www.youtube.com/watch?v=ZLSi-Oao9_w) this time. I hope this helps!
