### ISSUE TITLE
Yo can this be adressed??

### ISSUE THREAD

**Issue by DarkUrine** [AlizerUncaged/desktop-waifu#63]
Multiple people are facing the same issue and it's been left alone for weeks. The whole "Connection is already closed" text followed by the instructions to press any button to close. I have no idea how to fix this but I feel like it would be pretty easy for someone who understands this coding so I'm hoping we can all get some help with this issue so that we can enjoy this project as well. Thank you

![Screenshot 2023-06-05 020423](https://github.com/AlizerUncaged/desktop-waifu/assets/43804741/2d55328e-d9f6-4f51-9f6a-78928aa073b2)

**Comment by goodiesohhi** [comment]
Bruh. So did you solve it?

**Comment by DarkUrine** [comment]
Unfortunately not. I haven’t checked on the issues board to see if anyone has fixed it either though so it may already have a fix after this point. If not, god help us all lmao
