### ISSUE TITLE
is there a way to use this without an OpenAI account or a non-paid one??

### ISSUE THREAD

**Issue by Cappyadams** [AlizerUncaged/desktop-waifu#93]
(apologies for my english if it's bad-)
This is probably a stupid question. But is there a way to use this without an OpenAI account or atleast without paying for it? just askin cuz I sadly don't have the cash to pay for OpenAI.

**Comment by MepleYui** [comment]
https://github.com/AlizerUncaged/desktop-waifu/issues/47#issuecomment-1601966088

**Comment by Cappyadams** [comment]
> [#47 (comment)](https://github.com/AlizerUncaged/desktop-waifu/issues/47#issuecomment-1601966088)

Ah! Thanks!
